### ISSUE TITLE
Evaluation script error: 'VisionTransformer' object has no attribute 'input_patchnorm'

### ISSUE THREAD

**Issue by ethansmith2000** [YingqingHe/ScaleCrafter#28]
Traceback (most recent call last):
  File "scripts/evaluation/inference.py", line 137, in <module>
    run_inference(args, gpu_num, rank)
  File "scripts/evaluation/inference.py", line 115, in run_inference
    img_emb = model.get_image_embeds(cond_images)
  File "/home/ubuntu/VideoCrafter/scripts/evaluation/../../lvdm/models/ddpm3d.py", line 691, in get_image_embeds
    img_token = self.embedder(batch_imgs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/VideoCrafter/scripts/evaluation/../../lvdm/modules/encoders/condition.py", line 341, in forward
    z = self.encode_with_vision_transformer(image)
  File "/home/ubuntu/VideoCrafter/scripts/evaluation/../../lvdm/modules/encoders/condition.py", line 348, in encode_with_vision_transformer
    if self.model.visual.input_patchnorm:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'

**Comment by YingqingHe** [comment]
Hi. It seems that you were experimented with the VideoCrafter I2V model. Thanks for reporting that. For this issue, please comment out this if condition and its corresponding code: `if self.model.visual.input_ patchnorm:` in the VideoCrafter repo. Thanks! 🤗
